application: taskstopipeline
version: 1
runtime: python27
#runtime: python
api_version: 1
threadsafe: yes

handlers:
#- url: /favicon\.ico
#  static_files: favicon.ico
#  upload: favicon\.ico

- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt

#- url: /oauth2callback
#  script: oauth2client/appengine.py

#- url: /css
#  static_dir: css

- url: /assets
  static_dir: assets

- url: .*
  #script: main.py
  script: main.app
 
libraries:
- name: jinja2
  version: "2.6"

#- name: django
#  version: "1.2"
- name: webapp2
  version: "2.5.2"

- name: pycrypto
  version: "2.6"

- name: lxml
  version: "2.3"